services:
  downloader:
    build:
      context: .
      dockerfile: ./DownloadOrchestrator/Dockerfile
    ports:
      - "8081:8081"
      - "8080:8080"
    env_file:
      - ./DownloadOrchestrator/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./DownloadOrchestrator:/app/DownloadOrchestrator
    networks:
      - parser-network

  metar:
    build:
      context: .
      dockerfile: ./Parsers/MetarParser/src/scalabledataintegration/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - ./Parsers/MetarParser/.env
    environment:
      - BASE_URL=http://downloader:8080
      - PARSER_URL=http://metar:50051
    volumes:
      - ./Parsers/MetarParser/src:/app/Parsers/MetarParser/src
    networks:
      - parser-network
    depends_on:
      - downloader

networks:
  parser-network:
    driver: bridge