services:
  downloader:
    build: 
      context: .
      dockerfile: ./DownloadOrchestrator/Dockerfile
    ports:
      - "8081:8081"
      - "8080:8080"
    env_file:
      - ./DownloadOrchestrator/.env
    environment:
      - SERVER=${SERVER}
      - DATABASE=${DATABASE}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - BLOB_CONNECTION=${BLOB_CONNECTION}
      - KEY_VAULT_NAME=${KEY_VAULT_NAME}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - DD_API_KEY=${DD_API_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    volumes:
      - ./DownloadOrchestrator:/app/DownloadOrchestrator
    networks:
      - parser-network
  
  metar:
    build: 
      context: .
      dockerfile: ./Parsers/MetarParser/src/scalabledataintegration/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - ./Parsers/MetarParser/.env
    environment:
      - BASE_URL=http://downloader:8080
      - PARSER_NAME=${PARSER_NAME}
      - PARSER_URL=http://metar:50051
      - BLOB_CONNECTION=${BLOB_CONNECTION}
      - DD_API_KEY=${DD_API_KEY}
    volumes:
      - ./Parsers/MetarParser:/app/Parsers/MetarParser
    networks:
      - parser-network
    depends_on:
      - downloader

networks:
  parser-network:
    driver: bridge