# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'filter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66ilter.proto\x12\nsdi.filter\"X\n\rFilterRequest\x12\x10\n\x08raw_data\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\t\x12\x11\n\tnext_urls\x18\x04 \x01(\t\"@\n\x0b\x46ilterReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x07\x65rr_msg\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_err_msg2J\n\x06\x46ilter\x12@\n\nFilterCall\x12\x19.sdi.filter.FilterRequest\x1a\x17.sdi.filter.FilterReplyBIZGgithub.com/JonasKaad/ScalableDataIntegration/GeneratedClients/go/filterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZGgithub.com/JonasKaad/ScalableDataIntegration/GeneratedClients/go/filter'
  _globals['_FILTERREQUEST']._serialized_start=28
  _globals['_FILTERREQUEST']._serialized_end=116
  _globals['_FILTERREPLY']._serialized_start=118
  _globals['_FILTERREPLY']._serialized_end=182
  _globals['_FILTER']._serialized_start=184
  _globals['_FILTER']._serialized_end=258
# @@protoc_insertion_point(module_scope)
