# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parser.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparser.proto\x12\nsdi.parser\"k\n\x0cParseRequest\x12\x10\n\x08raw_data\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12.\n\x06\x66ilter\x18\x03 \x01(\x0b\x32\x19.sdi.parser.FilterRequestH\x00\x88\x01\x01\x42\t\n\x07_filter\"B\n\rParseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x07\x65rr_msg\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_err_msg\"/\n\rFilterRequest\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t2F\n\x06Parser\x12<\n\x05Parse\x12\x18.sdi.parser.ParseRequest\x1a\x19.sdi.parser.ParseResponseB<Z:github.com/JonasKaad/ScalableDataIntegration/protos/parserb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/JonasKaad/ScalableDataIntegration/protos/parser'
  _globals['_PARSEREQUEST']._serialized_start=28
  _globals['_PARSEREQUEST']._serialized_end=135
  _globals['_PARSERESPONSE']._serialized_start=137
  _globals['_PARSERESPONSE']._serialized_end=203
  _globals['_FILTERREQUEST']._serialized_start=205
  _globals['_FILTERREQUEST']._serialized_end=252
  _globals['_PARSER']._serialized_start=254
  _globals['_PARSER']._serialized_end=324
# @@protoc_insertion_point(module_scope)
