// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parser.proto

package sdi.parser;

public final class ParserOuterClass {
  private ParserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParseRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sdi.parser.ParseRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes raw_data = 1;</code>
     * @return The rawData.
     */
    com.google.protobuf.ByteString getRawData();

    /**
     * <code>string format = 2;</code>
     * @return The format.
     */
    java.lang.String getFormat();
    /**
     * <code>string format = 2;</code>
     * @return The bytes for format.
     */
    com.google.protobuf.ByteString
        getFormatBytes();

    /**
     * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
     * @return Whether the filter field is set.
     */
    boolean hasFilter();
    /**
     * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
     * @return The filter.
     */
    sdi.parser.ParserOuterClass.FilterRequest getFilter();
    /**
     * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
     */
    sdi.parser.ParserOuterClass.FilterRequestOrBuilder getFilterOrBuilder();
  }
  /**
   * Protobuf type {@code sdi.parser.ParseRequest}
   */
  public static final class ParseRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sdi.parser.ParseRequest)
      ParseRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParseRequest.newBuilder() to construct.
    private ParseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParseRequest() {
      rawData_ = com.google.protobuf.ByteString.EMPTY;
      format_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ParseRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sdi.parser.ParserOuterClass.internal_static_sdi_parser_ParseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sdi.parser.ParserOuterClass.internal_static_sdi_parser_ParseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sdi.parser.ParserOuterClass.ParseRequest.class, sdi.parser.ParserOuterClass.ParseRequest.Builder.class);
    }

    private int bitField0_;
    public static final int RAW_DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString rawData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes raw_data = 1;</code>
     * @return The rawData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRawData() {
      return rawData_;
    }

    public static final int FORMAT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object format_ = "";
    /**
     * <code>string format = 2;</code>
     * @return The format.
     */
    @java.lang.Override
    public java.lang.String getFormat() {
      java.lang.Object ref = format_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        format_ = s;
        return s;
      }
    }
    /**
     * <code>string format = 2;</code>
     * @return The bytes for format.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFormatBytes() {
      java.lang.Object ref = format_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILTER_FIELD_NUMBER = 3;
    private sdi.parser.ParserOuterClass.FilterRequest filter_;
    /**
     * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
     * @return Whether the filter field is set.
     */
    @java.lang.Override
    public boolean hasFilter() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
     * @return The filter.
     */
    @java.lang.Override
    public sdi.parser.ParserOuterClass.FilterRequest getFilter() {
      return filter_ == null ? sdi.parser.ParserOuterClass.FilterRequest.getDefaultInstance() : filter_;
    }
    /**
     * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
     */
    @java.lang.Override
    public sdi.parser.ParserOuterClass.FilterRequestOrBuilder getFilterOrBuilder() {
      return filter_ == null ? sdi.parser.ParserOuterClass.FilterRequest.getDefaultInstance() : filter_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!rawData_.isEmpty()) {
        output.writeBytes(1, rawData_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(format_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, format_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getFilter());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!rawData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, rawData_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(format_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, format_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getFilter());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sdi.parser.ParserOuterClass.ParseRequest)) {
        return super.equals(obj);
      }
      sdi.parser.ParserOuterClass.ParseRequest other = (sdi.parser.ParserOuterClass.ParseRequest) obj;

      if (!getRawData()
          .equals(other.getRawData())) return false;
      if (!getFormat()
          .equals(other.getFormat())) return false;
      if (hasFilter() != other.hasFilter()) return false;
      if (hasFilter()) {
        if (!getFilter()
            .equals(other.getFilter())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RAW_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getRawData().hashCode();
      hash = (37 * hash) + FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getFormat().hashCode();
      if (hasFilter()) {
        hash = (37 * hash) + FILTER_FIELD_NUMBER;
        hash = (53 * hash) + getFilter().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sdi.parser.ParserOuterClass.ParseRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sdi.parser.ParserOuterClass.ParseRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.ParseRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sdi.parser.ParserOuterClass.ParseRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.ParseRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sdi.parser.ParserOuterClass.ParseRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.ParseRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sdi.parser.ParserOuterClass.ParseRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sdi.parser.ParserOuterClass.ParseRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sdi.parser.ParserOuterClass.ParseRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.ParseRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sdi.parser.ParserOuterClass.ParseRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sdi.parser.ParserOuterClass.ParseRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sdi.parser.ParseRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sdi.parser.ParseRequest)
        sdi.parser.ParserOuterClass.ParseRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sdi.parser.ParserOuterClass.internal_static_sdi_parser_ParseRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sdi.parser.ParserOuterClass.internal_static_sdi_parser_ParseRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sdi.parser.ParserOuterClass.ParseRequest.class, sdi.parser.ParserOuterClass.ParseRequest.Builder.class);
      }

      // Construct using sdi.parser.ParserOuterClass.ParseRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFilterFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        rawData_ = com.google.protobuf.ByteString.EMPTY;
        format_ = "";
        filter_ = null;
        if (filterBuilder_ != null) {
          filterBuilder_.dispose();
          filterBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sdi.parser.ParserOuterClass.internal_static_sdi_parser_ParseRequest_descriptor;
      }

      @java.lang.Override
      public sdi.parser.ParserOuterClass.ParseRequest getDefaultInstanceForType() {
        return sdi.parser.ParserOuterClass.ParseRequest.getDefaultInstance();
      }

      @java.lang.Override
      public sdi.parser.ParserOuterClass.ParseRequest build() {
        sdi.parser.ParserOuterClass.ParseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sdi.parser.ParserOuterClass.ParseRequest buildPartial() {
        sdi.parser.ParserOuterClass.ParseRequest result = new sdi.parser.ParserOuterClass.ParseRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sdi.parser.ParserOuterClass.ParseRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rawData_ = rawData_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.format_ = format_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.filter_ = filterBuilder_ == null
              ? filter_
              : filterBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sdi.parser.ParserOuterClass.ParseRequest) {
          return mergeFrom((sdi.parser.ParserOuterClass.ParseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sdi.parser.ParserOuterClass.ParseRequest other) {
        if (other == sdi.parser.ParserOuterClass.ParseRequest.getDefaultInstance()) return this;
        if (other.getRawData() != com.google.protobuf.ByteString.EMPTY) {
          setRawData(other.getRawData());
        }
        if (!other.getFormat().isEmpty()) {
          format_ = other.format_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasFilter()) {
          mergeFilter(other.getFilter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                rawData_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                format_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getFilterFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString rawData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes raw_data = 1;</code>
       * @return The rawData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRawData() {
        return rawData_;
      }
      /**
       * <code>bytes raw_data = 1;</code>
       * @param value The rawData to set.
       * @return This builder for chaining.
       */
      public Builder setRawData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        rawData_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes raw_data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRawData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rawData_ = getDefaultInstance().getRawData();
        onChanged();
        return this;
      }

      private java.lang.Object format_ = "";
      /**
       * <code>string format = 2;</code>
       * @return The format.
       */
      public java.lang.String getFormat() {
        java.lang.Object ref = format_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          format_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string format = 2;</code>
       * @return The bytes for format.
       */
      public com.google.protobuf.ByteString
          getFormatBytes() {
        java.lang.Object ref = format_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          format_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string format = 2;</code>
       * @param value The format to set.
       * @return This builder for chaining.
       */
      public Builder setFormat(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        format_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string format = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFormat() {
        format_ = getDefaultInstance().getFormat();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string format = 2;</code>
       * @param value The bytes for format to set.
       * @return This builder for chaining.
       */
      public Builder setFormatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        format_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private sdi.parser.ParserOuterClass.FilterRequest filter_;
      private com.google.protobuf.SingleFieldBuilderV3<
          sdi.parser.ParserOuterClass.FilterRequest, sdi.parser.ParserOuterClass.FilterRequest.Builder, sdi.parser.ParserOuterClass.FilterRequestOrBuilder> filterBuilder_;
      /**
       * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
       * @return Whether the filter field is set.
       */
      public boolean hasFilter() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
       * @return The filter.
       */
      public sdi.parser.ParserOuterClass.FilterRequest getFilter() {
        if (filterBuilder_ == null) {
          return filter_ == null ? sdi.parser.ParserOuterClass.FilterRequest.getDefaultInstance() : filter_;
        } else {
          return filterBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
       */
      public Builder setFilter(sdi.parser.ParserOuterClass.FilterRequest value) {
        if (filterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          filter_ = value;
        } else {
          filterBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
       */
      public Builder setFilter(
          sdi.parser.ParserOuterClass.FilterRequest.Builder builderForValue) {
        if (filterBuilder_ == null) {
          filter_ = builderForValue.build();
        } else {
          filterBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
       */
      public Builder mergeFilter(sdi.parser.ParserOuterClass.FilterRequest value) {
        if (filterBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            filter_ != null &&
            filter_ != sdi.parser.ParserOuterClass.FilterRequest.getDefaultInstance()) {
            getFilterBuilder().mergeFrom(value);
          } else {
            filter_ = value;
          }
        } else {
          filterBuilder_.mergeFrom(value);
        }
        if (filter_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
       */
      public Builder clearFilter() {
        bitField0_ = (bitField0_ & ~0x00000004);
        filter_ = null;
        if (filterBuilder_ != null) {
          filterBuilder_.dispose();
          filterBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
       */
      public sdi.parser.ParserOuterClass.FilterRequest.Builder getFilterBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFilterFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
       */
      public sdi.parser.ParserOuterClass.FilterRequestOrBuilder getFilterOrBuilder() {
        if (filterBuilder_ != null) {
          return filterBuilder_.getMessageOrBuilder();
        } else {
          return filter_ == null ?
              sdi.parser.ParserOuterClass.FilterRequest.getDefaultInstance() : filter_;
        }
      }
      /**
       * <code>optional .sdi.parser.FilterRequest filter = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sdi.parser.ParserOuterClass.FilterRequest, sdi.parser.ParserOuterClass.FilterRequest.Builder, sdi.parser.ParserOuterClass.FilterRequestOrBuilder> 
          getFilterFieldBuilder() {
        if (filterBuilder_ == null) {
          filterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sdi.parser.ParserOuterClass.FilterRequest, sdi.parser.ParserOuterClass.FilterRequest.Builder, sdi.parser.ParserOuterClass.FilterRequestOrBuilder>(
                  getFilter(),
                  getParentForChildren(),
                  isClean());
          filter_ = null;
        }
        return filterBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sdi.parser.ParseRequest)
    }

    // @@protoc_insertion_point(class_scope:sdi.parser.ParseRequest)
    private static final sdi.parser.ParserOuterClass.ParseRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sdi.parser.ParserOuterClass.ParseRequest();
    }

    public static sdi.parser.ParserOuterClass.ParseRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParseRequest>
        PARSER = new com.google.protobuf.AbstractParser<ParseRequest>() {
      @java.lang.Override
      public ParseRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ParseRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParseRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sdi.parser.ParserOuterClass.ParseRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParseResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sdi.parser.ParseResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>optional string err_msg = 2;</code>
     * @return Whether the errMsg field is set.
     */
    boolean hasErrMsg();
    /**
     * <code>optional string err_msg = 2;</code>
     * @return The errMsg.
     */
    java.lang.String getErrMsg();
    /**
     * <code>optional string err_msg = 2;</code>
     * @return The bytes for errMsg.
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();
  }
  /**
   * Protobuf type {@code sdi.parser.ParseResponse}
   */
  public static final class ParseResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sdi.parser.ParseResponse)
      ParseResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParseResponse.newBuilder() to construct.
    private ParseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParseResponse() {
      errMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ParseResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sdi.parser.ParserOuterClass.internal_static_sdi_parser_ParseResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sdi.parser.ParserOuterClass.internal_static_sdi_parser_ParseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sdi.parser.ParserOuterClass.ParseResponse.class, sdi.parser.ParserOuterClass.ParseResponse.Builder.class);
    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_ = false;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int ERR_MSG_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object errMsg_ = "";
    /**
     * <code>optional string err_msg = 2;</code>
     * @return Whether the errMsg field is set.
     */
    @java.lang.Override
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string err_msg = 2;</code>
     * @return The errMsg.
     */
    @java.lang.Override
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errMsg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string err_msg = 2;</code>
     * @return The bytes for errMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sdi.parser.ParserOuterClass.ParseResponse)) {
        return super.equals(obj);
      }
      sdi.parser.ParserOuterClass.ParseResponse other = (sdi.parser.ParserOuterClass.ParseResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (hasErrMsg() != other.hasErrMsg()) return false;
      if (hasErrMsg()) {
        if (!getErrMsg()
            .equals(other.getErrMsg())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      if (hasErrMsg()) {
        hash = (37 * hash) + ERR_MSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrMsg().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sdi.parser.ParserOuterClass.ParseResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sdi.parser.ParserOuterClass.ParseResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.ParseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sdi.parser.ParserOuterClass.ParseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.ParseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sdi.parser.ParserOuterClass.ParseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.ParseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sdi.parser.ParserOuterClass.ParseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sdi.parser.ParserOuterClass.ParseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sdi.parser.ParserOuterClass.ParseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.ParseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sdi.parser.ParserOuterClass.ParseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sdi.parser.ParserOuterClass.ParseResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sdi.parser.ParseResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sdi.parser.ParseResponse)
        sdi.parser.ParserOuterClass.ParseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sdi.parser.ParserOuterClass.internal_static_sdi_parser_ParseResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sdi.parser.ParserOuterClass.internal_static_sdi_parser_ParseResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sdi.parser.ParserOuterClass.ParseResponse.class, sdi.parser.ParserOuterClass.ParseResponse.Builder.class);
      }

      // Construct using sdi.parser.ParserOuterClass.ParseResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        success_ = false;
        errMsg_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sdi.parser.ParserOuterClass.internal_static_sdi_parser_ParseResponse_descriptor;
      }

      @java.lang.Override
      public sdi.parser.ParserOuterClass.ParseResponse getDefaultInstanceForType() {
        return sdi.parser.ParserOuterClass.ParseResponse.getDefaultInstance();
      }

      @java.lang.Override
      public sdi.parser.ParserOuterClass.ParseResponse build() {
        sdi.parser.ParserOuterClass.ParseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sdi.parser.ParserOuterClass.ParseResponse buildPartial() {
        sdi.parser.ParserOuterClass.ParseResponse result = new sdi.parser.ParserOuterClass.ParseResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sdi.parser.ParserOuterClass.ParseResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.success_ = success_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.errMsg_ = errMsg_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sdi.parser.ParserOuterClass.ParseResponse) {
          return mergeFrom((sdi.parser.ParserOuterClass.ParseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sdi.parser.ParserOuterClass.ParseResponse other) {
        if (other == sdi.parser.ParserOuterClass.ParseResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.hasErrMsg()) {
          errMsg_ = other.errMsg_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                success_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                errMsg_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <code>optional string err_msg = 2;</code>
       * @return Whether the errMsg field is set.
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string err_msg = 2;</code>
       * @return The errMsg.
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string err_msg = 2;</code>
       * @return The bytes for errMsg.
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string err_msg = 2;</code>
       * @param value The errMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        errMsg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string err_msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrMsg() {
        errMsg_ = getDefaultInstance().getErrMsg();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string err_msg = 2;</code>
       * @param value The bytes for errMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        errMsg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sdi.parser.ParseResponse)
    }

    // @@protoc_insertion_point(class_scope:sdi.parser.ParseResponse)
    private static final sdi.parser.ParserOuterClass.ParseResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sdi.parser.ParserOuterClass.ParseResponse();
    }

    public static sdi.parser.ParserOuterClass.ParseResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParseResponse>
        PARSER = new com.google.protobuf.AbstractParser<ParseResponse>() {
      @java.lang.Override
      public ParseResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ParseResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParseResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sdi.parser.ParserOuterClass.ParseResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FilterRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sdi.parser.FilterRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes filter = 1;</code>
     * @return The filter.
     */
    com.google.protobuf.ByteString getFilter();

    /**
     * <code>string format = 2;</code>
     * @return The format.
     */
    java.lang.String getFormat();
    /**
     * <code>string format = 2;</code>
     * @return The bytes for format.
     */
    com.google.protobuf.ByteString
        getFormatBytes();
  }
  /**
   * Protobuf type {@code sdi.parser.FilterRequest}
   */
  public static final class FilterRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sdi.parser.FilterRequest)
      FilterRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FilterRequest.newBuilder() to construct.
    private FilterRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FilterRequest() {
      filter_ = com.google.protobuf.ByteString.EMPTY;
      format_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FilterRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sdi.parser.ParserOuterClass.internal_static_sdi_parser_FilterRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sdi.parser.ParserOuterClass.internal_static_sdi_parser_FilterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sdi.parser.ParserOuterClass.FilterRequest.class, sdi.parser.ParserOuterClass.FilterRequest.Builder.class);
    }

    public static final int FILTER_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString filter_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes filter = 1;</code>
     * @return The filter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFilter() {
      return filter_;
    }

    public static final int FORMAT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object format_ = "";
    /**
     * <code>string format = 2;</code>
     * @return The format.
     */
    @java.lang.Override
    public java.lang.String getFormat() {
      java.lang.Object ref = format_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        format_ = s;
        return s;
      }
    }
    /**
     * <code>string format = 2;</code>
     * @return The bytes for format.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFormatBytes() {
      java.lang.Object ref = format_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!filter_.isEmpty()) {
        output.writeBytes(1, filter_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(format_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, format_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!filter_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, filter_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(format_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, format_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sdi.parser.ParserOuterClass.FilterRequest)) {
        return super.equals(obj);
      }
      sdi.parser.ParserOuterClass.FilterRequest other = (sdi.parser.ParserOuterClass.FilterRequest) obj;

      if (!getFilter()
          .equals(other.getFilter())) return false;
      if (!getFormat()
          .equals(other.getFormat())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getFilter().hashCode();
      hash = (37 * hash) + FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getFormat().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sdi.parser.ParserOuterClass.FilterRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sdi.parser.ParserOuterClass.FilterRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.FilterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sdi.parser.ParserOuterClass.FilterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.FilterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sdi.parser.ParserOuterClass.FilterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.FilterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sdi.parser.ParserOuterClass.FilterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sdi.parser.ParserOuterClass.FilterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sdi.parser.ParserOuterClass.FilterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sdi.parser.ParserOuterClass.FilterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sdi.parser.ParserOuterClass.FilterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sdi.parser.ParserOuterClass.FilterRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sdi.parser.FilterRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sdi.parser.FilterRequest)
        sdi.parser.ParserOuterClass.FilterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sdi.parser.ParserOuterClass.internal_static_sdi_parser_FilterRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sdi.parser.ParserOuterClass.internal_static_sdi_parser_FilterRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sdi.parser.ParserOuterClass.FilterRequest.class, sdi.parser.ParserOuterClass.FilterRequest.Builder.class);
      }

      // Construct using sdi.parser.ParserOuterClass.FilterRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        filter_ = com.google.protobuf.ByteString.EMPTY;
        format_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sdi.parser.ParserOuterClass.internal_static_sdi_parser_FilterRequest_descriptor;
      }

      @java.lang.Override
      public sdi.parser.ParserOuterClass.FilterRequest getDefaultInstanceForType() {
        return sdi.parser.ParserOuterClass.FilterRequest.getDefaultInstance();
      }

      @java.lang.Override
      public sdi.parser.ParserOuterClass.FilterRequest build() {
        sdi.parser.ParserOuterClass.FilterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sdi.parser.ParserOuterClass.FilterRequest buildPartial() {
        sdi.parser.ParserOuterClass.FilterRequest result = new sdi.parser.ParserOuterClass.FilterRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sdi.parser.ParserOuterClass.FilterRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.filter_ = filter_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.format_ = format_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sdi.parser.ParserOuterClass.FilterRequest) {
          return mergeFrom((sdi.parser.ParserOuterClass.FilterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sdi.parser.ParserOuterClass.FilterRequest other) {
        if (other == sdi.parser.ParserOuterClass.FilterRequest.getDefaultInstance()) return this;
        if (other.getFilter() != com.google.protobuf.ByteString.EMPTY) {
          setFilter(other.getFilter());
        }
        if (!other.getFormat().isEmpty()) {
          format_ = other.format_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                filter_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                format_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString filter_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes filter = 1;</code>
       * @return The filter.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getFilter() {
        return filter_;
      }
      /**
       * <code>bytes filter = 1;</code>
       * @param value The filter to set.
       * @return This builder for chaining.
       */
      public Builder setFilter(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        filter_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes filter = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilter() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filter_ = getDefaultInstance().getFilter();
        onChanged();
        return this;
      }

      private java.lang.Object format_ = "";
      /**
       * <code>string format = 2;</code>
       * @return The format.
       */
      public java.lang.String getFormat() {
        java.lang.Object ref = format_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          format_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string format = 2;</code>
       * @return The bytes for format.
       */
      public com.google.protobuf.ByteString
          getFormatBytes() {
        java.lang.Object ref = format_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          format_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string format = 2;</code>
       * @param value The format to set.
       * @return This builder for chaining.
       */
      public Builder setFormat(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        format_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string format = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFormat() {
        format_ = getDefaultInstance().getFormat();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string format = 2;</code>
       * @param value The bytes for format to set.
       * @return This builder for chaining.
       */
      public Builder setFormatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        format_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sdi.parser.FilterRequest)
    }

    // @@protoc_insertion_point(class_scope:sdi.parser.FilterRequest)
    private static final sdi.parser.ParserOuterClass.FilterRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sdi.parser.ParserOuterClass.FilterRequest();
    }

    public static sdi.parser.ParserOuterClass.FilterRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FilterRequest>
        PARSER = new com.google.protobuf.AbstractParser<FilterRequest>() {
      @java.lang.Override
      public FilterRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FilterRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FilterRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sdi.parser.ParserOuterClass.FilterRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdi_parser_ParseRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sdi_parser_ParseRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdi_parser_ParseResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sdi_parser_ParseResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdi_parser_FilterRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sdi_parser_FilterRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014parser.proto\022\nsdi.parser\"k\n\014ParseReque" +
      "st\022\020\n\010raw_data\030\001 \001(\014\022\016\n\006format\030\002 \001(\t\022.\n\006" +
      "filter\030\003 \001(\0132\031.sdi.parser.FilterRequestH" +
      "\000\210\001\001B\t\n\007_filter\"B\n\rParseResponse\022\017\n\007succ" +
      "ess\030\001 \001(\010\022\024\n\007err_msg\030\002 \001(\tH\000\210\001\001B\n\n\010_err_" +
      "msg\"/\n\rFilterRequest\022\016\n\006filter\030\001 \001(\014\022\016\n\006" +
      "format\030\002 \001(\t2F\n\006Parser\022<\n\005Parse\022\030.sdi.pa" +
      "rser.ParseRequest\032\031.sdi.parser.ParseResp" +
      "onseB<Z:github.com/JonasKaad/ScalableDat" +
      "aIntegration/protos/parserb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sdi_parser_ParseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sdi_parser_ParseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sdi_parser_ParseRequest_descriptor,
        new java.lang.String[] { "RawData", "Format", "Filter", "Filter", });
    internal_static_sdi_parser_ParseResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sdi_parser_ParseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sdi_parser_ParseResponse_descriptor,
        new java.lang.String[] { "Success", "ErrMsg", "ErrMsg", });
    internal_static_sdi_parser_FilterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sdi_parser_FilterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sdi_parser_FilterRequest_descriptor,
        new java.lang.String[] { "Filter", "Format", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
